backend:
  name: github
  repo: ruppeledel-cyber/aslan
  branch: main
media_folder: "/"
public_folder: "/"
collections:
  - name: contenido
    label: Contenido de Aslan
    files:
      - file: content.json
        label: Datos de Aslan
        name: datos
        fields:
          - {label: Nombre, name: nombre, widget: string}
          - {label: Foto 1, name: foto1, widget: image}
          - {label: Foto 2, name: foto2, widget: image}
          - {label: Foto 3, name: foto3, widget: image}
          - {label: Presentación, name: intro, widget: text}
          - {label: Pelaje, name: pelaje, widget: string}
          - {label: Descripción, name: descripcion, widget: text}
          - {label: WhatsApp, name: whatsapp, widget: string}
